test

diff --git a/tools/init b/tools/init
--- a/tools/init
+++ b/tools/init
@@ -78,9 +78,15 @@ check_env() {
 }
 
 checkout_latest_release() {
-  hash=$(git log --grep="chore(release):" -1 --pretty="%H")
-  git reset --hard "$hash"
+  hash=$(git log --grep="chore(release):" -1 --pretty="%H" || true) # Capture output or return true if empty
+  if [ -n "$hash" ]; then # Check if hash is not empty
+    git reset --hard "$hash"
+  else
+    echo "Error: No release found in git log."
+    exit 1
+  fi
 }
+
 
 init_files() {
   if $_no_gh; then
